/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SEL63tVbvTD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";

import { Nav } from "./Nav";
import { Github, KeyRound, MoonStar } from "lucide-react";
import { Button } from "../ui/button";

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <Nav />
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 border-y">
          <div className="container px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Parcoil - Powering the Web
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Parcoil creates innovative web apps and online tools to
                  streamline your digital experience.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <Button asChild>
                  <Link href="/tools/password">
                    <KeyRound size={16} className="mr-1" />
                    Try Password Generator
                  </Link>
                </Button>
                <Button variant="secondary" asChild>
                  <Link href="https://lunaar.org?ref=parcoil">
                    <MoonStar size={16} className="mr-1" />
                    Explore Lunaar
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                  Open Source Projects
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Check out our latest open-source projects on GitHub and
                  contribute to the community.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="grid gap-4">
                <Link href="https://github.com/parcoil/sparkle">
                  <Card>
                    <CardHeader>
                      <CardTitle>parcoil/sparkle</CardTitle>
                      <CardDescription>Windows PC optimizer</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="flex space-x-4 text-sm text-gray-500 dark:text-gray-400">
                        <div className="flex items-center">
                          <CircleDotIcon className="mr-1 h-3 w-3 fill-yellow-300 text-yellow-300" />
                          JavaScript
                        </div>
                        <div className="flex items-center">
                          <StarIcon className="mr-1 h-3 w-3" />
                          500
                        </div>
                        <div>Updated May 2024</div>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
                <Link href="https://github.com/parcoil/lunaar.org">
                  <Card>
                    <CardHeader>
                      <CardTitle>parcoil/lunaar.org</CardTitle>
                      <CardDescription>
                        A modern gaming platform.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="flex space-x-4 text-sm text-gray-500 dark:text-gray-400">
                        <div className="flex items-center">
                          <CircleDotIcon className="mr-1 h-3 w-3 fill-yellow-300 text-yellow-300" />
                          Javascript
                        </div>
                        <div className="flex items-center">
                          <StarIcon className="mr-1 h-3 w-3" />
                          1.2k
                        </div>
                        <div>Updated April 2024</div>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
              </div>
              <div className="flex flex-col justify-center space-y-4">
                <Button>
                  <Github size={20} className="mr-1" />
                  <Link href="https://github.com/parcoil">View on GitHub</Link>
                </Button>
                <p className="text-gray-500 dark:text-gray-400">
                  Explore our growing collection of open-source projects and
                  contribute to the community.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Parcoil. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-xs hover:underline underline-offset-4"
            href="/tos"
          >
            Terms of Service
          </Link>
          <Link
            className="text-xs hover:underline underline-offset-4"
            href="/pp"
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function CircleDotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="1" />
    </svg>
  );
}

function PinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="17" y2="22" />
      <path d="M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z" />
    </svg>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
