/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/a4oJVrMYxN3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"

import Image from "next/image";
export function NavBar() {
  return (
    (<header
      key="1"
      className="flex items-center justify-between h-16 px-4 md:px-6 bg-white shadow dark:bg-gray-950">
      <Link className="flex items-center gap-2 text-lg font-semibold" href="/./">
     
        <Image src={'/logo.png'} className="" width={50} height={50}/>
        <span className="sr-only">Parcoil</span>
      </Link>
      <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
        <Link
          className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
          href="/./">
          Home
        </Link>
        <Link
          className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
          href="#">
          iOS/Siri Shortcuts
        </Link>
        <Link
          className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
          href="https://lunaar.org">
          Games
        </Link>
        <Link
          className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
          href="#">
          App Store
        </Link>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Link
              className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300 flex items-center gap-1"
              href="#">
              Tools
              <ChevronDownIcon className="h-4 w-4" />
            </Link>
          </DropdownMenuTrigger>
          <DropdownMenuContent className="w-48">
            <DropdownMenuItem>
              <Link
                className="block px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-100 dark:text-gray-50 dark:hover:bg-gray-800"
                href="/./tools/password">
                Password Manager
              </Link>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </nav>
      <div className="flex items-center gap-2 md:hidden">
        <Sheet>
          <SheetTrigger asChild>
            <Button className="flex items-center gap-2" size="sm" variant="outline">
              <MenuIcon className="h-5 w-5" />
              <span className="sr-only">Toggle menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent className="w-[280px]" side="right">
            <div className="flex flex-col gap-4 p-4">
              <Link
                className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
                href="#">
                Home
              </Link>
              <Link
                className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
                href="#">
                iOS/Siri Shortcuts
              </Link>
              <Link
                className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
                href="https://lunaar.org">
                Games
              </Link>
              <Link
                className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300"
                href="#">
                App Store
              </Link>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <div className="flex items-center justify-between gap-2 cursor-pointer">
                    <span
                      className="text-gray-900 hover:text-gray-700 dark:text-gray-50 dark:hover:text-gray-300">
                      Tools
                    </span>
                    <ChevronDownIcon className="h-4 w-4" />
                  </div>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="w-48">
                  <DropdownMenuItem>
                    <Link
                      className="block px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-100 dark:text-gray-50 dark:hover:bg-gray-800"
                      href="#">
                      Password Manager
                    </Link>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </SheetContent>
        </Sheet>
      </div>
    </header>)
  );
}

function ChevronDownIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m6 9 6 6 6-6" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
