import { Nav } from "@/components/component/Nav";
import React from "react";

function page() {
  return (
    <>
      <Nav />
      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-4 text-center">
          Terms of Service
        </h1>
        <p>
          <strong>Parcoil, Inc.</strong>
        </p>
        <p className="mb-4">Last Updated: 6/1/24</p>
        <p>
          <strong>Address:</strong>
          <br />
          Parcoil, Inc.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>
          By accessing and using the Parcoil website and services, you agree to
          comply with and be bound by these Terms of Service ("Terms"). If you
          do not agree to these Terms, please do not use our services.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">2. Changes to Terms</h2>
        <p>
          Parcoil reserves the right to modify these Terms at any time. Any
          changes will be effective immediately upon posting on our website.
          Your continued use of our services following the posting of changes
          will constitute your acceptance of those changes.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">3. Use of Services</h2>
        <p>
          You agree to use our services only for lawful purposes and in
          accordance with these Terms. You are responsible for all activities
          that occur under your account.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">4. Payments</h2>
        <p>
          All payments for Parcoil services are due in full at the time of
          purchase. We do not offer refunds for any reason.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">5. No Refund Policy</h2>
        <p>
          All sales are final. No refunds will be issued under any
          circumstances.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">
          6. User-Generated Content
        </h2>
        <p>
          Parcoil is not responsible for any content generated by users of our
          services. You acknowledge that all user-generated content is the sole
          responsibility of the person who created such content.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">
          7. Release of Liability
        </h2>
        <p>
          You agree to release, indemnify, and hold harmless Parcoil, its
          affiliates, and their respective officers, directors, employees, and
          agents from any and all claims, liabilities, damages, and expenses
          arising out of your use of our services.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">8. Analytics</h2>
        <p>
          Parcoil may use third-party analytics services to collect and analyze
          data about your use of our services. By using our services, you
          consent to the collection and use of this data.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">
          9. Third-Party Data Processors
        </h2>
        <p>
          Parcoil may use third-party service providers to process your data.
          These providers are contractually obligated to protect your
          information and use it only for the purposes for which it was
          disclosed.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">10. Arbitration</h2>
        <p>
          Any disputes arising out of or related to these Terms or our services
          will be resolved through binding arbitration in accordance with the
          rules of the American Arbitration Association.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">11. DMCA Compliance</h2>
        <p>
          Parcoil complies with the Digital Millennium Copyright Act (DMCA). If
          you believe your copyright-protected work has been infringed, please
          contact our DMCA Agent at:
        </p>
        <p>
          <strong>DMCA Agent</strong>
          <br />
          Parcoil, Inc.
          <br />
          Email: <a href="mailto:dmca@parcoil.com">dmca@parcoil.com</a>
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">
          12. Basic Privacy Policy
        </h2>
        <p>
          Parcoil is committed to protecting your privacy. We collect, use, and
          share your personal information as described in our Privacy Policy. By
          using our services, you consent to the collection and use of your
          information in accordance with our Privacy Policy.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">13. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws
          of the State of [State], without regard to its conflict of law
          principles.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Contact Information</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p>
          Parcoil, Inc.
          <br />
          Email: <a href="mailto:info@parcoil.com">info@parcoil.com</a>
        </p>
      </div>
    </>
  );
}

export default page;
