import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
 import { ToastContainer } from 'react-toastify';
import { NavBar } from "@/components/component/nav-bar";
import { getAuth } from 'firebase/auth';
import { initializeApp } from 'firebase/app';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firebaseConfig = {
  apiKey: "AIzaSyABFTePIUCzlSbZWLuYpPyvqIJgn5uQBpU",
  authDomain: "parcoil.firebaseapp.com",
  projectId: "parcoil",
  storageBucket: "parcoil.appspot.com",
  messagingSenderId: "620906474969",
  appId: "1:620906474969:web:6e11c631d03e253fd8fdc8",
  measurementId: "G-FQ8PQ7DD0P"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
<ToastContainer
position="bottom-center"
autoClose={5000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="colored"
/>
        {children}
        </body>
    </html>
  );
}
